name: Android Lint

on:
  push:
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  checkLint:
    runs-on: ubuntu-latest
    steps:
      - uses: uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Run Linter
        run: ./gradlew lint -x :rclone:buildAll
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Lint Reports
          path: ~/**/build/reports/
          retention-days: 30
